first_10_hotels = [
    "https://www.tripadvisor.com/Hotel_Review-g293974-d1732739-Reviews-Hotel_Sultania-Istanbul.html",
    "https://www.tripadvisor.com/Hotel_Review-g297983-d1773066-Reviews-Divan_Cave_House-Goreme_Cappadocia.html",
    "https://www.tripadvisor.com/Hotel_Review-g20116893-d568401-Reviews-Liberty_Hotels_Lara-Kemeragzi_Antalya_Turkish_Mediterranean_Coast.html",
    "https://www.tripadvisor.com/Hotel_Review-g15300585-d557049-Reviews-Lara_Barut_Collection-Muratpasa_Antalya_Turkish_Mediterranean_Coast.html",
    "https://www.tripadvisor.com/Hotel_Review-g293974-d8364987-Reviews-Romance_Istanbul_Hotel-Istanbul.html",
    "https://www.tripadvisor.com/Hotel_Review-g20116893-d572784-Reviews-Concorde_De_Luxe_Resort-Kemeragzi_Antalya_Turkish_Mediterranean_Coast.html",
    "https://www.tripadvisor.com/Hotel_Review-g293974-d14930175-Reviews-Sheraton_Istanbul_City_Center-Istanbul.html",
    "https://www.tripadvisor.com/Hotel_Review-g293974-d2049041-Reviews-The_Story_Hotel_Pera-Istanbul.html",
    "https://www.tripadvisor.com/Hotel_Review-g312725-d507974-Reviews-Rixos_Premium_Belek_The_Land_Of_Legends_Access-Belek_Serik_District_Turkish_Mediterrane.html",
    "https://www.tripadvisor.com/Hotel_Review-g297983-d18220399-Reviews-Aza_Cave_Hotel-Goreme_Cappadocia.html"","
]

new_links = [
    "https://www.tripadvisor.com/Hotel_Review-g312737-d499760-Reviews-Turk_Hotel-Oludeniz_Fethiye_Mugla_Province_Turkish_Aegean_Coast.html",
    "https://www.tripadvisor.com/Hotel_Review-g1192197-d677125-Reviews-Utopia_World_Hotel-Kargicak_Alanya_Turkish_Mediterranean_Coast.html",
    "https://www.tripadvisor.com/Hotel_Review-g950910-d951547-Reviews-Mukarnas_Resort_And_Spa_Hotel-Okurcalar_Alanya_Turkish_Mediterranean_Coast.html",
    "https://www.tripadvisor.com/Hotel_Review-g312725-d8006067-Reviews-Sueno_Hotels_Deluxe_Belek-Belek_Serik_District_Turkish_Mediterranean_Coast.html",
    "https://www.tripadvisor.com/Hotel_Review-g1192102-d10595797-Reviews-Bosphorus_Sorgun_Hotel-Sorgun_Manavgat_Turkish_Mediterranean_Coast.html",
    "https://www.tripadvisor.com/Hotel_Review-g1467692-d1101505-Reviews-Anadolu_Hotels_Didim_Club-Altinkum_Didim_Turkish_Aegean_Coast.html",
    "https://www.tripadvisor.com/Hotel_Review-g950910-d508026-Reviews-Justiniano_Club_Alanya-Okurcalar_Alanya_Turkish_Mediterranean_Coast.html",
    "https://www.tripadvisor.com/Hotel_Review-g23456196-d295927-Reviews-SeaLife_Family_Resort_Hotel-Konyaalti_Antalya_Turkish_Mediterranean_Coast.html",
    "https://www.tripadvisor.com/Hotel_Review-g663346-d664985-Reviews-XL_Hotels-Sarigerme_Mugla_Province_Turkish_Aegean_Coast.html",
    "https://www.tripadvisor.com/Hotel_Review-g298033-d315018-Reviews-Club_Anastasia-Marmaris_Marmaris_District_Mugla_Province_Turkish_Aegean_Coast.html",
    "https://www.tripadvisor.com/Hotel_Review-g312725-d1160045-Reviews-Selin_Hotel_Spa_Belek-Belek_Serik_District_Turkish_Mediterranean_Coast.html",
    "https://www.tripadvisor.com/Hotel_Review-g297968-d6394853-Reviews-Oz_Hotels_Side_Premium-Side_Manavgat_Turkish_Mediterranean_Coast.html",
    "https://www.tripadvisor.com/Hotel_Review-g951014-d1989064-Reviews-Bera_Hotel_Alanya-Konakli_Alanya_Turkish_Mediterranean_Coast.html",
    "https://www.tripadvisor.com/Hotel_Review-g312725-d530563-Reviews-Pine_Beach_Belek-Belek_Serik_District_Turkish_Mediterranean_Coast.html",
    "https://www.tripadvisor.com/Hotel_Review-g297968-d1910355-Reviews-Selge_Hotel_Side-Side_Manavgat_Turkish_Mediterranean_Coast.html",
    "https://www.tripadvisor.com/Hotel_Review-g293974-d1574146-Reviews-Fors_Hotel-Istanbul.html",
    "https://www.tripadvisor.com/Hotel_Review-g18423752-d672440-Reviews-Azure_By_Yelken_Hotel-Peksimet_Bodrum_District_Mugla_Province_Turkish_Aegean_Coast.html",
    "https://www.tripadvisor.com/Hotel_Review-g297961-d4474814-Reviews-Cleopatra_Golden_Beach_Hotel-Alanya_Turkish_Mediterranean_Coast.html",
    "https://www.tripadvisor.com/Hotel_Review-g297961-d599531-Reviews-A11_Hotel_Alanya-Alanya_Turkish_Mediterranean_Coast.html",
    "https://www.tripadvisor.com/Hotel_Review-g297983-d18220399-Reviews-Aza_Cave_Hotel-Goreme_Cappadocia.html",
    "https://www.tripadvisor.com/Hotel_Review-g297987-d6104787-Reviews-Ramada_by_Wyndham_Cappadocia-Ortahisar_Cappadocia.html",
    "https://www.tripadvisor.com/Hotel_Review-g25352709-d508169-Reviews-Kustur_Club_Holiday_Village-Bayraklidede_Kusadasi_Turkish_Aegean_Coast.html",
    "https://www.tripadvisor.com/Hotel_Review-g27720871-d9733093-Reviews-Aquasis_De_Luxe_Resort_Spa-Camlik_Didim_Turkish_Aegean_Coast.html",
    "https://www.tripadvisor.com/Hotel_Review-g18423752-d1553772-Reviews-Sianji_Well_Being_Resort-Peksimet_Bodrum_District_Mugla_Province_Turkish_Aegean_Coas.html",
    "https://www.tripadvisor.com/Hotel_Review-g297961-d663636-Reviews-Blue_Star_Hotel-Alanya_Turkish_Mediterranean_Coast.html",
    "https://www.tripadvisor.com/Hotel_Review-g1069655-d6220173-Reviews-Xafira_Deluxe_Resort_Spa-Turkler_Alanya_Turkish_Mediterranean_Coast.html",
    "https://www.tripadvisor.com/Hotel_Review-g297961-d1197403-Reviews-or40-Mesut_Hotel-Alanya_Turkish_Mediterranean_Coast.html",
    "https://www.tripadvisor.com/Hotel_Review-g312725-d625934-Reviews-Adam_Eve-Belek_Serik_District_Turkish_Mediterranean_Coast.html",
    "https://www.tripadvisor.com/Hotel_Review-g293974-d27430829-Reviews-Joyway_Hotels_Istanbul_Sultanahmet-Istanbul.html",
    "https://www.tripadvisor.com/Hotel_Review-g298033-d673676-Reviews-Grand_Pasa_Hotel-Marmaris_Marmaris_District_Mugla_Province_Turkish_Aegean_Coast.html",
    "https://www.tripadvisor.com/Hotel_Review-g2540176-d4945597-Reviews-Hattusa_Vacation_Thermal_Club_Kazdaglari-Gure_Turkish_Aegean_Coast.html",
    "https://www.tripadvisor.com/Hotel_Review-g609056-d1134071-Reviews-Hotel_Eda-Icmeler_Marmaris_District_Mugla_Province_Turkish_Aegean_Coast.html",
    "https://www.tripadvisor.com/Hotel_Review-g17951017-d9705613-Reviews-Trendy_Lara-Aksu_Antalya_Turkish_Mediterranean_Coast.html",
    "https://www.tripadvisor.com/Hotel_Review-g297968-d23977211-Reviews-Side_Win_Hotel_Spa-Side_Manavgat_Turkish_Mediterranean_Coast.html",
    "https://www.tripadvisor.com/Hotel_Review-g297968-d9587648-Reviews-Glamour_Resort_Spa-Side_Manavgat_Turkish_Mediterranean_Coast.html",
    "https://www.tripadvisor.com/Hotel_Review-g297961-d9793384-Reviews-The_Lumos_Deluxe_Resort_Hotel_Spa-Alanya_Turkish_Mediterranean_Coast.html",
    "https://www.tripadvisor.com/Hotel_Review-g951437-d1412957-Reviews-Kefaluka_Resort_Bodrum-Akyarlar_Turgutreis_Bodrum_District_Mugla_Province_Turkish_Aege.html",
    "https://www.tripadvisor.com/Hotel_Review-g297968-d26933240-Reviews-Side_Moon_Palace_Hotel-Side_Manavgat_Turkish_Mediterranean_Coast.html",
    "https://www.tripadvisor.com/Hotel_Review-g298661-d300579-Reviews-Goddess_of_Bodrum-Gumbet_Bodrum_District_Mugla_Province_Turkish_Aegean_Coast.html",
    "https://www.tripadvisor.com/Hotel_Review-g1069655-d647590-Reviews-Long_Beach_Alanya-Turkler_Alanya_Turkish_Mediterranean_Coast.html",
    "https://www.tripadvisor.com/Hotel_Review-g293974-d1962076-Reviews-Crowne_Plaza_Istanbul_Harbiye_By_Ihg-Istanbul.html",
    "https://www.tripadvisor.com/Hotel_Review-g297961-d23102453-Reviews-Miarosa_KonaklI_Garden-Alanya_Turkish_Mediterranean_Coast.html",
    "https://www.tripadvisor.com/Hotel_Review-g4833191-d23597414-Reviews-Prenses_Sealine_Beach_Hotel-Bogazkent_Serik_District_Turkish_Mediterranean_Coast.html",
    "https://www.tripadvisor.com/Hotel_Review-g293974-d20234737-Reviews-The_First_Ottoman_Suites-Istanbul.html",
    "https://www.tripadvisor.com/Hotel_Review-g1554819-d1631851-Reviews-Selectum_family_comfort-Kizilagac_Manavgat_Turkish_Mediterranean_Coast.html",
    "https://www.tripadvisor.com/Hotel_Review-g293974-d294614-Reviews-Hilton_Istanbul_Bosphorus-Istanbul.html",
    "https://www.tripadvisor.com/Hotel_Review-g298033-d300033-Reviews-Elegance_Hotels_International_Marmaris-Marmaris_Marmaris_District_Mugla_Province_Turkis.html",
    "https://www.tripadvisor.com/Hotel_Review-g1193628-d3268956-Reviews-Senza_Grand_Santana_Hotel-Mahmutlar_Turkish_Mediterranean_Coast.html",
    "https://www.tripadvisor.com/Hotel_Review-g670690-d618813-Reviews-Musti_s_Royal_Hotel_Plaza-Armutalan_Marmaris_District_Mugla_Province_Turkish_Aegean_Coa.html",
    "https://www.tripadvisor.com/Hotel_Review-g293974-d8542939-Reviews-Doubletree_By_Hilton_Istanbul_Piyalepasa-Istanbul.html",
    "https://www.tripadvisor.com/Hotel_Review-g297961-d2723311-Reviews-Rosella_Hotel-Alanya_Turkish_Mediterranean_Coast.html",
    "https://www.tripadvisor.com/Hotel_Review-g297961-d647591-Reviews-Kleopatra_Beach_Hotel-Alanya_Turkish_Mediterranean_Coast.html",
    "https://www.tripadvisor.com/Hotel_Review-g612463-d603503-Reviews-Richmond_Nua_Wellness_Spa-Sapanca_Sakarya_Province.html",
    "https://www.tripadvisor.com/Hotel_Review-g298031-d553651-Reviews-Club_Tuana_Fethiye-Fethiye_Mugla_Province_Turkish_Aegean_Coast.html",
    "https://www.tripadvisor.com/Hotel_Review-g297961-d6891351-Reviews-Kleopatra_Atlas_Hotel-Alanya_Turkish_Mediterranean_Coast.html",
    "https://www.tripadvisor.com/Hotel_Review-g312738-d675860-Reviews-Delta_Hotels_by_Mariott_Bodrum-Yalikavak_Bodrum_District_Mugla_Province_Turkish_Aegean_.html",
    "https://www.tripadvisor.com/Hotel_Review-g298014-d298870-Reviews-Grand_Hotel_Konya-Konya.html",
    "https://www.tripadvisor.com/Hotel_Review-g1186137-d2265331-Reviews-Daima_Biz_Hotel-Kiris_Kemer_Turkish_Mediterranean_Coast.html",
    "https://www.tripadvisor.com/Hotel_Review-g312725-d647913-Reviews-Belkon_Hotel-Belek_Serik_District_Turkish_Mediterranean_Coast.html",
    "https://www.tripadvisor.com/Hotel_Review-g293974-d304797-Reviews-The_Green_Park_Taksim-Istanbul.html",
    "https://www.tripadvisor.com/Hotel_Review-g297966-d7909836-Reviews-Grand_Ring_Hotel-Kemer_Turkish_Mediterranean_Coast.html",
    "https://www.tripadvisor.com/Hotel_Review-g297966-d1159758-Reviews-Palmet_Turkiz_Hotel-Kemer_Turkish_Mediterranean_Coast.html",
    "https://www.tripadvisor.com/Hotel_Review-g297972-d550997-Reviews-Ladonia_Hotels_Adakule-Kusadasi_Turkish_Aegean_Coast.html",
    "https://www.tripadvisor.com/Hotel_Review-g297962-d301300-Reviews-Hotel_Su_Aqualand-Antalya_Turkish_Mediterranean_Coast.html",
    "https://www.tripadvisor.com/Hotel_Review-g1467692-d1416620-Reviews-Seahorse_Deluxe_Hotel-Altinkum_Didim_Turkish_Aegean_Coast.html",
    "https://www.tripadvisor.com/Hotel_Review-g298033-d1717875-Reviews-Cihanturk_Hotel-Marmaris_Marmaris_District_Mugla_Province_Turkish_Aegean_Coast.html",
    "https://www.tripadvisor.com/Hotel_Review-g297966-d951583-Reviews-Daima_Resort_Hotel-Kemer_Turkish_Mediterranean_Coast.html",
    "https://www.tripadvisor.com/Hotel_Review-g12078952-d23426767-Reviews-Alarcha_Hotels_Resort-Boztepe_Manavgat_Turkish_Mediterranean_Coast.html",
    "https://www.tripadvisor.com/Hotel_Review-g609052-d6155844-Reviews-Rubi_Platinum_Spa_Resort_Suites-Avsallar_Alanya_Turkish_Mediterranean_Coast.html",
    "https://www.tripadvisor.com/Hotel_Review-g297962-d656476-Reviews-Hotel_Karyatit-Antalya_Turkish_Mediterranean_Coast.html",
]

first_10_hotels = set(first_10_hotels)
new_links = set(new_links)

final_set = new_links - first_10_hotels

print("New, unique links.  ", len(new_links), " ", len(final_set), ": ")
for link in final_set:
    print(link)